"""initial schema

Revision ID: 234002042d33
Revises: 
Create Date: 2026-09-14 14:50:38.945073
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '234002042d33'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('igdb_id', sa.Integer(), nullable=True),
    sa.Column('steam_appid', sa.Integer(), nullable=True),
    sa.Column('developer', sa.String(length=255), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('genres', sa.JSON(), nullable=False),
    sa.Column('themes', sa.JSON(), nullable=False),
    sa.Column('perspectives', sa.JSON(), nullable=False),
    sa.Column('modes', sa.JSON(), nullable=False),
    sa.Column('hours_main', sa.Float(), nullable=True),
    sa.Column('hours_complete', sa.Float(), nullable=True),
    sa.Column('avg_session_minutes', sa.Integer(), nullable=True),
    sa.Column('platforms', sa.JSON(), nullable=False),
    sa.Column('requirements', sa.JSON(), nullable=True),
    sa.Column('critic_score', sa.Float(), nullable=True),
    sa.Column('cover_url', sa.String(length=512), nullable=True),
    sa.Column('hero_url', sa.String(length=512), nullable=True),
    sa.Column('screenshots', sa.JSON(), nullable=False),
    sa.Column('videos', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('igdb_id'),
    sa.UniqueConstraint('steam_appid')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_games_title'), ['title'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('steam_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('friendships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('addressee_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('pending', 'accepted', name='friendstate'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['addressee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_id', 'addressee_id', name='uq_friend_pair')
    )
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_friendships_addressee_id'), ['addressee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_friendships_requester_id'), ['requester_id'], unique=False)

    op.create_table('library_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('backlog', 'playing', 'completed', 'abandoned', 'wishlist', name='status'), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('hours_played', sa.Float(), nullable=False),
    sa.Column('last_played', sa.DateTime(timezone=True), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'game_id', name='uq_user_game')
    )
    with op.batch_alter_table('library_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_library_entries_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_library_entries_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_library_entries_game_id'))

    op.drop_table('library_entries')
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_friendships_requester_id'))
        batch_op.drop_index(batch_op.f('ix_friendships_addressee_id'))

    op.drop_table('friendships')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_title'))
        batch_op.drop_index(batch_op.f('ix_games_slug'))

    op.drop_table('games')
    # ### end Alembic commands ###
